(#9) - Add dotnet-core.yml workflow
corgibytes/freshli-cli pull request #12
Opened 2021-03-23 01:13 UTC by mfcorgi

2021-03-24 15:25 UTC, mrbiggred requested changes
The Command Line Interface (CLI) does not produce a NuGet package.  The steps that pack and publish the NuGet package should be removed from the build.

The result of this build should be an executable (exe) with the correct version number set.  Case #9 is to put the built exe somewhere after it is built.

2021-03-24 15:25 UTC, mrbiggred commented on .github/workflows/dotnet-core.yml
> +        run: dotnet pack -c Release
The CLI does not produce a NuGet package.  The "Package" and "Publish Alpha Package to GitHub Packages" can be removed.

2021-03-31 21:10 UTC, mrbiggred requested changes
This looks the same as PR #17.  Should one of the PRs be discarded?

2021-04-01 15:11 UTC, mfcorgi commented
Closing this PR because the ci.yml file was already pushed in #17

2021-04-01 15:11 UTC, closed without merging