Disable omitting class name from constructor
corgibytes/freshli-cli pull request #143
Opened 2022-07-22 08:55 UTC by edwinkortman

2022-07-28 17:27 UTC, mscottford requested changes
I'm okay with the direction of this change because the `new(new(new(` that we've seen in a few places has been confusing. But I would like to see us use `var` in cases where there would otherwise be `TypeName value = new TypeName`.

2022-07-28 17:27 UTC, mscottford commented on Corgibytes.Freshli.Cli.Test/CommandOptions/ScanCommandOptionsTest.cs
> +        Parser parser = new Parser(cmBuilder.Command);
This should become:

```suggestion
        var parser = new Parser(cmBuilder.Command);
```

2022-08-03 20:56 UTC, mscottford commented on Corgibytes.Freshli.Cli.Test/CommandOptions/ScanCommandOptionsTest.cs
> +        Parser parser = new Parser(cmBuilder.Command);
I've addressed this in recent commits.

2022-08-03 20:57 UTC, mscottford approved these changes

2022-08-03 23:09 UTC, donabp approved these changes
everything looks good and clean, it's ready for a merge! :)

2022-08-04 16:08 UTC, mscottford commented
recheck

2022-08-04 16:46 UTC, mscottford commented
recheck

2022-08-04 16:53 UTC, merged