(#12) - Add codeclimate + codecoverage
corgibytes/freshli-cli pull request #17
Opened 2021-03-23 21:05 UTC by mfcorgi

2021-03-24 16:48 UTC, mrbiggred requested changes
This PR might need to be discarded and re-created depending on how we deal with #7 and #9.  Please also add the Code Climate badges to the Readme like in Freshli Lib:

https://github.com/corgibytes/freshli-lib/blob/main/README.md

2021-03-24 16:48 UTC, mrbiggred commented on .github/workflows/dotnet-core.yml
> +        run: dotnet nuget push ./Freshli.Cli/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate -n true -s https://nuget.pkg.github.com/corgibytes/index.json
The above package creating and push can be removed.  There is no NuGet package for the command line.

2021-03-24 16:48 UTC, mrbiggred commented on .github/workflows/dotnet-core.yml
> +            ${{github.workspace}}/Freshli.Cli.Test/coverage.info:lcov
👍

2021-03-24 16:48 UTC, mrbiggred commented on .codeclimate.yml
> +  - "Freshli.Cli.Test/obj/**"
👍

2021-03-31 21:05 UTC, mrbiggred approved these changes
The PR looks fine to me.  I'm curious that the difference between this PR and PR #12 are?  It appears like the `ci.yml` files are the same.  Should one PR be deleted?

I do have a question about why the release is only updated on pushes and not PRs?  Is that to prevent the release from getting updated if a PR is not merged?

@dfar-io originally convinced me to have a separate release notes job in #corgibytes/freshli-lib#249.  Now you have convinced me to combine it back to one file.  Like you I can't think of a good way to upload the exe in a separate GitHub action.  Maybe we, or someone else, will come up with a better solution but for now one CI file is good.

2021-03-31 21:16 UTC, mfcorgi commented on .github/workflows/ci.yml
> +          assets: 'freshli-cli-${{ steps.gitversion.outputs.majorMinorPatch }}-win-x64.zip,freshli-cli-${{ steps.gitversion.outputs.majorMinorPatch }}-linux-x64.zip,freshli-cli-${{ steps.gitversion.o
It replaces an asset if already exists or upload a new asset. It will not delete assets with different names than the one being uploaded.

2021-03-31 21:20 UTC, mfcorgi commented
> The PR looks fine to me. I'm curious that the difference between this PR and PR #12 are? It appears like the `ci.yml` files are the same. Should one PR be deleted?
> 
> I do have a question about why the release is only updated on pushes and not PRs? Is that to prevent the release from getting updated if a PR is not merged?
> 
> @dfar-io originally convinced me to have a separate release notes job in #[corgibytes/freshli-lib#249](https://github.com/corgibytes/freshli-lib/pull/249). Now you have convinced me to combine it back to one file. Like you I can't think of a good way to upload the exe in a separate GitHub action. Maybe we, or someone else, will come up with a better solution but for now one CI file is good.

Yes, it is the same file. I was going to rebase once the other PR is approved. I added it here because this steps needs to be added in that file. We can close the other PR and merge only this and that will work.

Regarding a different files. Both previous files were applied on the same situation. (push or pr to master or release branche) I believe we need to keep one to upload draft artifacts, which is part of the CI workflow. For sure we need a different release workflow but to create a final release.

Regarding your other sentence, yes. you are correct, I do not update the draft release on MR because

1) we can have more than 1 PR for the same branch, which will override the artifact and we are never going to know which is the one attached  to the draft. 
2)  To prevent the release from getting updated if a PR is not merged.

If we want the executable for that particular workflow, we can go to the workflow artifacts.

2021-04-01 15:00 UTC, merged